Add build and deploy job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -165,3 +165,65 @@ jobs:
       run: bin/rspec spec
       env:
         DATABASE_URL: postgresql://microbrewers:password@localhost/
+
+  build:
+    runs-on: ubuntu-latest
+    needs: [rspec, rubocop, zeitwerk, brakeman, yarn_eslint, yarn_stylelint]
+    outputs:
+      app_env: ${{ steps.meta.outputs.app_env }}
+      digest: ${{ steps.build_app.outputs.digest }}
+    if: github.ref == 'refs/heads/production' || github.ref == 'refs/heads/staging' || github.event_name == 'schedule' || github.ref == 'refs/heads/continuous-deployment'
+    steps:
+      - name: "Set up meta"
+        id: meta
+        run: |
+          if [ "$GITHUB_REF" == "refs/heads/staging" ]; then
+            APP_ENV=staging
+          elif [ "$GITHUB_REF" == "refs/heads/production" ]; then
+            APP_ENV=production
+          elif [ "$GITHUB_REF" == "refs/heads/continuous-deployment" ]; then
+            APP_ENV=production
+          else
+          echo "⚠️ Could not determine app env for branch ${{ env.BRANCH_NAME }}"
+          exit 1
+          fi
+
+          echo "::set-output name=app_env::$APP_ENV"
+      - name: "Checkout repository"
+        uses: actions/checkout@v2
+      - name: "Set up Docker Buildx"
+        uses: docker/setup-buildx-action@v1
+      - name: Cache Docker layers
+        uses: actions/cache@v2
+        with:
+          path: /tmp/.buildx-cache
+          key: ${{ runner.os }}-buildx-${{ github.sha }}
+          restore-keys: |
+            ${{ runner.os }}-buildx-
+      - name: Login to OCIR
+        uses: docker/login-action@v1
+        with:
+          registry: fra.ocir.io
+          username: ${{ secrets.OCI_USERNAME }}
+          password: ${{ secrets.OCI_PASSWORD }}
+      - name: Build and push app
+        id: build_app
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          build-args: |
+              GIT_REV=${{ github.sha }}`
+          push: true
+          tags: |
+              fra.ocir.io/${{ secrets.OCI_NAMESPACE }}/microbrewers-${{ steps.meta.outputs.app_env }}:${{ github.sha }}
+          cache-from: type=local,src=/tmp/.buildx-cache
+          cache-to: type=local,dest=/tmp/.buildx-cache-new
+          no-cache: ${{ github.event_name == 'schedule' }}
+
+      # Temp fix
+      # https://github.com/docker/build-push-action/issues/252
+      # https://github.com/moby/buildkit/issues/1896
+      - name: Move cache
+        run: |
+          rm -rf /tmp/.buildx-cache
+          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
